name: Update Trading Data

on:
#  schedule:
#    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Add this

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Update trading data
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          # Replace both placeholders
          sed -i "s/your_google_api_key_here/$GOOGLE_API_KEY/g" updateTradingData.js
          sed -i "s/your_sheet_id_here/$GOOGLE_SHEET_ID/g" updateTradingData.js
          npm run update-trading

      - name: Commit and push if data changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add src/data/liveTrading.ts
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Auto-update trading data from Google Sheets"
            git push
          fi
